sudo: required
services:
    - docker

before_install:
    - docker build -t awalom/docker-react -f Dockerfile.dev .

script:
    - docker run awalom/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-296707627731"
    bucket_path: "docker-react"
    on:
        branch: master

